version: 0.2
phases:
    install:
       run-as: root
       on-failure: abort
       commands:
          - chmod 777 $CODEBUILD_SRC_DIR/scripts/install_agents.sh
          - $CODEBUILD_SRC_DIR/scripts/install_agents.sh
       finally:
          - echo "install phase completed successfully"   
    pre_build:
        run-as: root
        on-failure: abort
        commands:
           - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_REPO
        finally:
           - echo "sucessfully authenticated with ecr repo"   
    build:
        run-as: root
        on-failure: abort
        commands:
           - docker build -t eksdemo .
           - docker tag eksdemo:latest $ECR_REPO/$TAG
           - docker push $ECR_REPO/$TAG                  
artifacts:
   files:
     - SampleWebApp.war               