version: 0.2
phases:
    install:
       run-as: root
       on-failure: abort
       commands:
          - chmod 777 $CODEBUILD_SRC_DIR/scripts/install_agents.sh
          - $CODEBUILD_SRC_DIR/scripts/install_agents.sh
       finally:
          - echo "install phase completed successfully"   
    pre_build:
        run-as: root
        on-failure: abort
        commands:
           - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 160281779685.dkr.ecr.ap-south-1.amazonaws.com
        finally:
           - echo "sucessfully authenticated with ecr repo"   
    build:
        run-as: root
        on-failure: abort
        commands:
           - docker build -t eksdemo .
           - docker tag eksdemo:latest 160281779685.dkr.ecr.ap-south-1.amazonaws.com/demo123:latest
           - docker push 160281779685.dkr.ecr.ap-south-1.amazonaws.com/demo123:latest                  
artifacts:
   files:
     - SampleWebApp.war               